name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg?palette=github-dark

      - name: Commit and push snake.svg
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snake.svg
          git commit -m "Generate snake.svg animation" || echo "No changes to commit"
          git push
